
spring:
  application:
    name: regist-web
#  redis:
#    host: 47.111.237.99
#    port: 6380
#    password: 123456
#    jedis:
#      pool:
#        max-active: 20

server:
  port: 7762


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000