spring:
  application:
    name: store-shop-web-order
  rabbitmq:
    host: 120.26.130.33
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: nz1905
  redis:
    host: 120.26.130.33
    port: 6379
    client-name:
    password:

server:
  port: 8085
