server:
  port: 8080

spring:
  application:
    name: store-shop-web-zc-pay
  redis:
    port: 6379
    host: 120.26.130.33
    password: 851880
    jedis:
      pool:
        max-active: 20

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


